---
title: "diversity"
output: html_notebook
---

```{r}
library(tidyverse)
library(qiime2R)
library(phyloseq)
library(patchwork)

```



Read in metadata

```{r}

metadata_bc <- read_delim("./from_zhen/bc_map_metadata.txt") %>%
  mutate(`day-of-operation` = as.numeric(`day-of-operation`))
metadata_ss <- read_delim("./from_zhen/ss_map_metadata.txt") %>%
  mutate(`day-of-operation` = as.numeric(`day-of-operation`))

metadata_all <- bind_rows(metadata_bc, metadata_ss) %>%
  rename(day = `day-of-operation`) %>%
  filter(day <= 276)

rm(metadata_bc, metadata_ss)


```

plotting prefs + reference files
```{r}

source("./scripts/plotting.R")

```


read in phyloseq + make diversity objects
```{r}
ps_all <- qza_to_phyloseq(features = "./from_zhen/table_all.qza",
                          taxonomy = "./from_zhen/taxonomy_5.3.qza")

# alpha diversity
min(sample_sums(ps_all))
    
ps_rare <- rarefy_even_depth(ps_all, sample.size = 10000,
  replace = TRUE, trimOTUs = TRUE)

alpha_div_plt <- plot_richness(ps_rare)

alpha_div <- alpha_div_plt$data %>%
  right_join(metadata_all, by = c("samples" = "sample-id")) 

rm(alpha_div_plt)

# beta diversity

beta_ord <- ordinate(ps_rare, method = "PCoA", distance = "bray")

# beta_div <- as.data.frame(beta_ord$points) %>%
#   rownames_to_column("samples") %>%
#   right_join(metadata_all, by = c("samples" = "sample-id")) 
   
beta_div <- as.data.frame(beta_ord$vectors) %>%
  rownames_to_column("samples") %>%
  right_join(metadata_all, by = c("samples" = "sample-id")) 


```


```{r}
alpha_div %>%
  filter(variable %in% c("Chao1", "Shannon")) %>%
  ggplot(., aes(x = day, y = value, color = location, shape = location)) +
  facet_wrap(~variable, scales = "free") + 
  geom_point() +
  theme_classic() +
  labs(x = "Day of Operation", y = "Diversity measure") +
  scale_color_manual(values = location_cols, name = "Location") +
  scale_shape_manual(values = c(15, 16), name = "Location") +
  scale_x_continuous(breaks = seq(0, 300, by = 50)) +
  # ylim(2.5, 6) + 
  theme(legend.position = "top")

ggsave("./figures/alpha_diversity.png", width = 8, height = 4, units = "in", dpi = 320)
  
```


```{r}
beta_div %>%
  ggplot(., aes(x = Axis.1, y = Axis.2, color = day, shape = location)) +
  geom_point() +
  theme_classic() +
  theme(legend.position = "top")

ggsave("./figures/beta_diversity.png", width = 4, height = 3, units = "in", dpi = 320)
```





